import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import path from "path";
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository (https://github.com/GitHub-Xzhi/obsidian-remember-settings-window) of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const distDir = "dist";
const localeDefaultsDir = path.join("src", "locale", "defaults");

// Node 14 回退：fs.globSync 是 Node 22+ 才有的 API
function globFiles(pattern, cwd) {
    if (typeof fs.globSync === "function") {
        return fs.globSync(pattern, { cwd });
    }
    const dir = path.dirname(pattern);
    const ext = path.extname(pattern);
    const fullDir = path.resolve(cwd, dir);
    try {
        return fs.readdirSync(fullDir)
            .filter(f => f.endsWith(ext))
            .map(f => path.join(dir, f).split(path.sep).join("/"));
    } catch {
        return [];
    }
}

/** 复制默认 locale JSON 文件到 dist/locale/ */
function copyLocaleDefaults() {
    const srcDir = localeDefaultsDir;
    const destDir = path.join(distDir, "locale");
    if (!fs.existsSync(srcDir)) return;
    if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });
    for (const file of fs.readdirSync(srcDir)) {
        if (file.endsWith(".json")) {
            const dest = path.join(destDir, file);
            // 不覆盖已有文件（保护用户自定义翻译）
            if (!fs.existsSync(dest)) {
                fs.copyFileSync(path.join(srcDir, file), dest);
            }
        }
    }
    console.log(`Locale defaults copied → ${destDir}/`);
}

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    plugins: [{
        name: "import-glob",
        setup: (build) => {
            build.onResolve({ filter: /^glob:.*$/ }, async (args) => {
                return {
                    path: args.path.replace(/^glob:/, ''),
                    namespace: 'import-glob',
                    pluginData: { resolveDir: args.resolveDir },
                };
            });
            build.onLoad({ filter: /.*/, namespace: 'import-glob' }, async (args) => {
                const files = globFiles(args.path, args.pluginData.resolveDir).sort();
                return {
                    contents: [
                        ...files.map((module, i) => `import m${i} from './${module}'`),
                        "export default {",
                            ...files.map((f, i) => `${JSON.stringify(path.basename(f, path.extname(f)))}: m${i},`),
                        "}",
                    ].join("\n"),
                    resolveDir: args.pluginData.resolveDir,
                };
            });
        },
    }],
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtinModules,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outdir: distDir,
    minify: prod,
});

if (prod) {
    await context.rebuild();
    // 复制 manifest.json 到 dist 目录
    fs.copyFileSync("manifest.json", path.join(distDir, "manifest.json"));
    // 复制默认 locale 文件到 dist/locale/
    copyLocaleDefaults();
    console.log(`Build complete → ${distDir}/`);
    process.exit(0);
} else {
    // 开发模式：确保 dist 有 manifest.json 和 locale 默认值
    if (!fs.existsSync(path.join(distDir, "manifest.json"))) {
        fs.copyFileSync("manifest.json", path.join(distDir, "manifest.json"));
    }
    copyLocaleDefaults();
    await context.watch();
}
